#  Ex110 - Add to the coin.py module created in the previous challenges, a
# function called summary(), which shows on the screen some information
# generated by the functions we already have in the module created so
# far.

import coin

p = float(input('Enter price: $'))
coin.summary(p, 15, 15)
